apiVersion: v1
kind: Secret
metadata:
  name: sqsboto3-flask-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: Your_Access_Key_Id_encoded
  AWS_SECRET_ACCESS_KEY: Your_Secret_Access_Key_encoded
  AWS_REGION: Aws_region_encoded 